var HexukiWasm=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var f=moduleArg,aa="./this.program",m="",ba;try{m=(new URL(".",_scriptName)).href}catch{}ba=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var da=console.log.bind(console),t=console.error.bind(console),u,w=!1,x,ea,fa,A,C,D,E,F,G,ha,ia,H,ja,ka=!1;
function la(){var a=I.buffer;A=new Int8Array(a);D=new Int16Array(a);C=new Uint8Array(a);E=new Uint16Array(a);F=new Int32Array(a);G=new Uint32Array(a);ha=new Float32Array(a);ia=new Float64Array(a);H=new BigInt64Array(a);ja=new BigUint64Array(a)}function ma(a){f.onAbort?.(a);a="Aborted("+a+")";t(a);w=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");fa?.(a);throw a;}var J;
async function na(a){if(!u)try{var b=await ba(a);return new Uint8Array(b)}catch{}if(a==J&&u)a=new Uint8Array(u);else throw"both async and sync fetching of the wasm failed";return a}async function oa(a,b){try{var c=await na(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),ma(d)}}
async function pa(a){var b=J;if(!u)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return oa(b,a)}class qa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var ra=a=>{for(;0<a.length;)a.shift()(f)},sa=[],ta=[],ua=()=>{var a=f.preRun.shift();ta.push(a)},K=!0;class va{constructor(a){this.aa=a-24}}
var wa=0,xa=0,M=a=>{for(var b="";;){var c=C[a++];if(!c)return b;b+=String.fromCharCode(c)}},N={},O={},P={},Q=class extends Error{constructor(a){super(a);this.name="BindingError"}},ya=a=>{throw new Q(a);};function za(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(O.hasOwnProperty(a)){if(c.ca)return;throw new Q(`Cannot register type '${d}' twice`);}O[a]=b;delete P[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(e=>e()))}
function R(a,b,c={}){return za(a,b,c)}var Aa=(a,b,c)=>{switch(b){case 1:return c?d=>A[d]:d=>C[d];case 2:return c?d=>D[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>H[d>>3]:d=>ja[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ba=[],S=[0,1,,1,null,1,!0,1,!1,1],Ca=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ba.pop()||S.length;S[b]=a;S[b+1]=1;return b}};
function T(a){return this.W(G[a>>2])}var Da={name:"emscripten::val",W:a=>{if(!a)throw new Q(`Cannot use deleted val. handle = ${a}`);var b=S[a];9<a&&0===--S[a+1]&&(S[a]=void 0,Ba.push(a));return b},Z:(a,b)=>Ca(b),$:T,Y:null},Ea=(a,b)=>{switch(b){case 4:return function(c){return this.W(ha[c>>2])};case 8:return function(c){return this.W(ia[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Fa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ga(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Y)return!0;return!1}
var Ha=(a,b)=>{if(void 0===f[a].X){var c=f[a];f[a]=function(...d){if(!f[a].X.hasOwnProperty(d.length))throw new Q(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${f[a].X})!`);return f[a].X[d.length].apply(this,d)};f[a].X=[];f[a].X[c.ba]=c}},Ia=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].X&&void 0!==f[a].X[c])throw new Q(`Cannot register public name '${a}' twice`);Ha(a,a);if(f[a].X.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].X[c]=b}else f[a]=b,f[a].ba=c},Ja=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},Ka=class extends Error{constructor(a){super(a);this.name="InternalError"}},Oa=[],Qa=(a,b)=>{a=M(a);var c;(c=Oa[b])||(Oa[b]=c=Pa.get(b));if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c};class Ra extends Error{}
var Ta=a=>{a=Sa(a);var b=M(a);U(a);return b},Ua=(a,b)=>{function c(g){e[g]||O[g]||(P[g]?P[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Ra(`${a}: `+d.map(Ta).join([", "]));},Va=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Ka("Mismatched type converter count");for(var l=0;l<d.length;++l)R(d[l],k[l])}var d=[];d.forEach(k=>P[k]=a);var e=Array(a.length),g=[],h=0;a.forEach((k,l)=>{O.hasOwnProperty(k)?e[l]=O[k]:(g.push(k),N.hasOwnProperty(k)||(N[k]=[]),N[k].push(()=>
{e[l]=O[k];++h;h===g.length&&c(e)}))});0===g.length&&c(e)},Wa=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},V=(a,b,c)=>{var d=C;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=
128|h&63;g++}}d[b]=0;return b-e},Xa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ya=globalThis.TextDecoder&&new TextDecoder,Za=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},$a=(a,b=0,c,d)=>{c=Za(a,b,c,d);if(16<c-b&&a.buffer&&Ya)return Ya.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&
240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},ab=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,bb=(a,b,c)=>{a>>=1;b=Za(E,a,b/2,c);if(16<b-a&&ab)return ab.decode(E.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(E[a]);return c},cb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=
a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d},db=a=>2*a.length,eb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var g=G[a+e];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},fb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.codePointAt(e);65535<g&&e++;F[b>>2]=g;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},gb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},W=0,X={},hb=a=>{if(!(a instanceof qa||"unwind"==a))throw a;},ib=
a=>{x=a;K||0<W||(f.onExit?.(a),w=!0);throw new qa(a);},jb=a=>{if(!w)try{if(a(),!(K||0<W))try{x=a=x,ib(a)}catch(b){hb(b)}}catch(b){hb(b)}},Y={},lb=()=>{if(!kb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in Y)void 0===Y[b]?delete a[b]:a[b]=Y[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);kb=c}return kb},kb,mb=[null,[],[]],nb=()=>a=>crypto.getRandomValues(a),
ob=a=>{(ob=nb())(a)};f.noExitRuntime&&(K=f.noExitRuntime);f.print&&(da=f.print);f.printErr&&(t=f.printErr);f.wasmBinary&&(u=f.wasmBinary);f.thisProgram&&(aa=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var pb,Sa,qb,U,I,Pa,rb={e:(a,b,c)=>{var d=new va(a);G[d.aa+16>>2]=0;G[d.aa+4>>2]=b;G[d.aa+8>>2]=c;wa=a;xa++;throw wa;},w:()=>ma(""),g:(a,b,c,d,e)=>{b=M(b);d=0n===d;let g=h=>h;if(d){const h=8*c;g=k=>BigInt.asUintN(h,k);e=g(e)}R(a,{name:b,W:g,Z:(h,k)=>{"number"==typeof k&&(k=BigInt(k));return k},$:Aa(b,c,!d),Y:null})},j:(a,b,c,d)=>{b=M(b);R(a,{name:b,W:function(e){return!!e},Z:function(e,g){return g?c:d},$:function(e){return this.W(C[e])},Y:null})},h:a=>R(a,Da),f:(a,b,c)=>{b=M(b);R(a,{name:b,W:d=>d,
Z:(d,e)=>e,$:Ea(b,c),Y:null})},b:(a,b,c,d,e,g,h)=>{var k=Ja(b,c);a=M(a);a=Wa(a);e=Qa(d,e);Ia(a,function(){Ua(`Cannot call ${a} due to unbound types`,k)},b-1);Va(k,l=>{var q=a;var y=a;l=[l[0],null].concat(l.slice(1));var z=e,n=l.length;if(2>n)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var B=null!==l[1]&&!1,L=Ga(l),La=!l[0].da,p=l[0],v=l[1];z=[y,ya,z,g,Fa,p.W.bind(p),v?.Z.bind(v)];for(p=2;p<n;++p)v=l[p],z.push(v.Z.bind(v));if(!L)for(p=B?1:2;p<l.length;++p)null!==
l[p].Y&&z.push(l[p].Y);L=Ga(l);p=l.length-2;var r=[];v=["fn"];B&&v.push("thisWired");for(n=0;n<p;++n)r.push(`arg${n}`),v.push(`arg${n}Wired`);r=r.join(",");v=v.join(",");r=`return function (${r}) {\n`;L&&(r+="var destructors = [];\n");var Ma=L?"destructors":"null",ca="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");B&&(r+=`var thisWired = toClassParamWire(${Ma}, this);\n`);for(n=0;n<p;++n){var Na=`toArg${n}Wire`;r+=`var arg${n}Wired = ${Na}(${Ma}, arg${n});\n`;
ca.push(Na)}r+=(La||h?"var rv = ":"")+`invoker(${v});\n`;if(L)r+="runDestructors(destructors);\n";else for(n=B?1:2;n<l.length;++n)B=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==l[n].Y&&(r+=`${B}_dtor(${B});\n`,ca.push(`${B}_dtor`));La&&(r+="var ret = fromRetWire(rv);\nreturn ret;\n");l=(new Function(ca,r+"}\n"))(...z);y=Object.defineProperty(l,"name",{value:y});l=b-1;if(!f.hasOwnProperty(q))throw new Ka("Replacing nonexistent public symbol");void 0!==f[q].X&&void 0!==l?f[q].X[l]=y:(f[q]=y,f[q].ba=
l);return[]})},c:(a,b,c,d,e)=>{b=M(b);let g=k=>k;if(0===d){var h=32-8*c;g=k=>k<<h>>>h;e=g(e)}R(a,{name:b,W:g,Z:(k,l)=>l,$:Aa(b,c,0!==d),Y:null})},a:(a,b,c)=>{function d(g){return new e(A.buffer,G[g+4>>2],G[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=M(c);R(a,{name:c,W:d,$:d},{ca:!0})},i:(a,b)=>{b=M(b);R(a,{name:b,W(c){var d=(d=c+4)?$a(C,d,G[c>>2],!0):"";U(c);return d},Z(c,d){d instanceof ArrayBuffer&&
(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new Q("Cannot pass non-string to std::string");var g=e?Xa(d):d.length;var h=pb(4+g+1),k=h+4;G[h>>2]=g;e?V(d,k,g+1):C.set(d,k);null!==c&&c.push(U,h);return h},$:T,Y(c){U(c)}})},d:(a,b,c)=>{c=M(c);if(2===b){var d=bb;var e=cb;var g=db}else d=eb,e=fb,g=gb;R(a,{name:c,W:h=>{var k=d(h+4,G[h>>2]*b,!0);U(h);return k},Z:(h,k)=>{if("string"!=typeof k)throw new Q(`Cannot pass non-string to C++ string type ${c}`);
var l=g(k),q=pb(4+l+b);G[q>>2]=l/b;e(k,q+4,l+b);null!==h&&h.push(U,q);return q},$:T,Y(h){U(h)}})},p:(a,b)=>{b=M(b);R(a,{da:!0,name:b,W:()=>{},Z:()=>{}})},l:()=>{K=!1;W=0},m:(a,b)=>{X[a]&&(clearTimeout(X[a].id),delete X[a]);if(!b)return 0;var c=setTimeout(()=>{delete X[a];jb(()=>qb(a,performance.now()))},b);X[a]={id:c,ea:b};return 0},o:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();G[a>>2]=60*Math.max(g,e);F[b>>2]=Number(g!=
e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(V(a,c,17),V(b,d,17)):(V(a,d,17),V(b,c,17))},x:function(a,b,c){if(!(0<=a&&3>=a))return 28;H[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},y:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-I.buffer.byteLength+
65535)/65536|0;try{I.grow(d);la();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},q:(a,b)=>{var c=0,d=0,e;for(e of lb()){var g=b+c;G[a+d>>2]=g;c+=V(e,g,Infinity)+1;d+=4}return 0},r:(a,b)=>{var c=lb();G[a>>2]=c.length;a=0;for(var d of c)a+=Xa(d)+1;G[b>>2]=a;return 0},s:()=>52,v:()=>52,t:function(){return 70},u:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var h=G[b>>2],k=G[b+4>>2];b+=8;for(var l=0;l<k;l++){var q=a,y=C[h+l],z=mb[q];0===y||10===y?((1===q?da:t)($a(z)),z.length=0):z.push(y)}e+=k}G[d>>
2]=e;return 0},k:ib,n:(a,b)=>{ob(C.subarray(a,a+b));return 0}},Z;
Z=await (async function(){function a(c){c=Z=c.exports;f._wasmInitialize=c.B;f._wasmReset=c.C;f._wasmLoadPosition=c.D;f._wasmSavePosition=c.E;f._wasmGetCurrentPlayer=c.F;f._wasmGetScoreP1=c.G;f._wasmGetScoreP2=c.H;f._wasmIsGameOver=c.I;f._wasmGetTileValue=c.J;f._wasmMakeMove=c.K;f._wasmUnmakeMove=c.L;f._wasmGetValidMovesCount=c.M;f._wasmGetValidMoves=c.N;f._wasmMCTSFindBestMove=c.O;f._wasmMinimaxFindBestMove=c.P;f._wasmCleanup=c.Q;pb=c.R;Sa=c.S;qb=c.T;U=c.V;I=c.z;Pa=c.U;la();return Z}var b=
{a:rb};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});J??=f.locateFile?f.locateFile("hexuki.wasm",m):m+"hexuki.wasm";return a((await pa(b)).instance)}());
(function(){function a(){f.calledRun=!0;if(!w){ka=!0;Z.A();ea?.(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();sa.push(b)}ra(sa)}}if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ua();ra(ta);f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()})();ka?moduleRtn=f:moduleRtn=new Promise((a,b)=>{ea=a;fa=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=HexukiWasm;module.exports.default=HexukiWasm}else if(typeof define==="function"&&define["amd"])define([],()=>HexukiWasm);
